# Generated by Django 4.2.28 on 2026-02-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_billing_date_expense_is_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('expense', 'One-time Expense'), ('subscription', 'Subscription'), ('sip', 'SIP Investment'), ('emi', 'EMI / Loan'), ('insurance', 'Insurance')], default='expense', max_length=20),
        ),
    ]
