# Generated by Django 4.2.28 on 2026-02-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_expense_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='billing_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='billing_period',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
