# Generated by Django 4.2.28 on 2026-02-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
