# Generated by Django 4.2.28 on 2026-02-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_expense_next_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='months_paid',
            field=models.IntegerField(default=0, help_text='Number of months already billed/reminded'),
        ),
        migrations.AddField(
            model_name='expense',
            name='subscription_months',
            field=models.IntegerField(blank=True, help_text='Total months to run the subscription', null=True),
        ),
    ]
