# Generated by Django 4.2.28 on 2026-02-24 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0008_expense_months_paid_expense_subscription_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('target_amount', models.FloatField(help_text='Total amount to save')),
                ('monthly_salary', models.FloatField(help_text='User in-hand monthly salary')),
                ('months_target', models.IntegerField(help_text='Total months planned')),
                ('monthly_saving', models.FloatField(help_text='Planned saving per month (target / months)')),
                ('months_done', models.IntegerField(default=0)),
                ('amount_saved', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monthly_data', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
