# Generated by Django 4.2.28 on 2026-03-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='goal',
            name='amount_saved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='goal',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, help_text='User in-hand monthly salary', max_digits=12),
        ),
        migrations.AlterField(
            model_name='goal',
            name='monthly_saving',
            field=models.DecimalField(decimal_places=2, help_text='Planned saving per month (target / months)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount to save', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'date'], name='finance_exp_user_id_03e8ce_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'billing_day', 'is_active'], name='finance_exp_user_id_62aa34_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_type'], name='finance_exp_expense_f68925_idx'),
        ),
    ]
